# Generated by Django 4.1.2 on 2022-11-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sunt_un_idiot',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
